[icp]
canister_id="uxrrr-q7777-77774-qaaaq-cai"
agent_url="http://localhost:4943"

[ethereum]
consensus_api="https://ethereum.operationsolarstorm.org"
execution_api="https://ethereum-rpc.publicnode.com"
checkpoint_sync_host="https://sync-mainnet.beaconcha.in"
genesis_validator_root="4b363db94e286120d76eb905340fdd4e54bfe9f06bf33ff6cf5ad27f511bfe95"
genesis_time=1606824023
forks.genesis = { epoch = 0, fork_version = "00000000" }
forks.altair = { epoch = 74240, fork_version = "01000000" }
forks.bellatrix = { epoch = 144896, fork_version = "02000000" }
forks.capella = { epoch = 194048, fork_version = "03000000" }
forks.deneb = { epoch = 269568, fork_version = "04000000" }
forks.electra = { epoch = 364032, fork_version = "05000000" }

[ethereum_holesky]
execution_apis = [ "https://holesky.drpc.org" ]